<?php

namespace Container5kCEjcl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYIe7sxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tYIe7sx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tYIe7sx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'interviewrep' => ['privates', 'App\\Repository\\InterviewRepository', 'getInterviewRepositoryService', true],
        ], [
            'entityManager' => '?',
            'interviewrep' => 'App\\Repository\\InterviewRepository',
        ]);
    }
}
