<?php

namespace ContainerHURynmF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_JIprolAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.jIprolA' shared service.
     *
     * @return \App\Controller\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\SecurityController::resetpassword()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?');
    }
}
