<?php

namespace ContainerHURynmF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Dq4s4haService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Dq4s4ha' shared service.
     *
     * @return \App\Controller\Swift_Mailer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\SecurityController::forgotPassword()": the $mailer argument is type-hinted with the non-existent class or interface: "App\\Controller\\Swift_Mailer". Did you forget to add a use statement?');
    }
}
