<?php

namespace ContainerHURynmF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KjJ7sCEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KjJ7sCE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KjJ7sCE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['privates', '.errored.jIprolA', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::resetpassword()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.l9JDN.c', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::resetpassword()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'passwordEncoder' => '?',
            'request' => '?',
        ]);
    }
}
