security:
    enable_authenticator_manager: true

    # Définissez les hasheurs de mot de passe pour vos utilisateurs
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthAuthenticator
            logout:
                path: app_logout
                target: /app_user # Redirection après déconnexion
