twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
form_themes:
    - bootstrap_4_layout.html.twig 

framework:
    validation:
        enable_annotations: true
