<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Freelancer extends \App\Entity\Freelancer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'cv', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'portfolio_link', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'bio', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'evaluation'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'cv', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'portfolio_link', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'bio', '' . "\0" . 'App\\Entity\\Freelancer' . "\0" . 'evaluation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Freelancer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCv(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCv', []);

        return parent::getCv();
    }

    /**
     * {@inheritDoc}
     */
    public function setCv(string $cv): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCv', [$cv]);

        return parent::setCv($cv);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortfolioLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortfolioLink', []);

        return parent::getPortfolioLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortfolioLink(string $portfolio_link): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortfolioLink', [$portfolio_link]);

        return parent::setPortfolioLink($portfolio_link);
    }

    /**
     * {@inheritDoc}
     */
    public function getBio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBio', []);

        return parent::getBio();
    }

    /**
     * {@inheritDoc}
     */
    public function setBio(string $bio): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBio', [$bio]);

        return parent::setBio($bio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluation', []);

        return parent::getEvaluation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvaluation(?int $evaluation): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvaluation', [$evaluation]);

        return parent::setEvaluation($evaluation);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullName(string $full_name): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullName', [$full_name]);

        return parent::setFullName($full_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

}
