<?php

namespace ContainerDcyJXRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AS_Ov95Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aS.ov95' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aS.ov95'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\JobsController::list' => ['privates', '.service_locator.eGZADws', 'get_ServiceLocator_EGZADwsService', true],
            'App\\Controller\\PostulationController::addPostulation' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostulationController::deletePostulation' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostulationController::list' => ['privates', '.service_locator.7Vvo5dt', 'get_ServiceLocator_7Vvo5dtService', true],
            'App\\Controller\\PostulationController::showPost' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PostulationController::updatepost' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\JobsController:list' => ['privates', '.service_locator.eGZADws', 'get_ServiceLocator_EGZADwsService', true],
            'App\\Controller\\PostulationController:addPostulation' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostulationController:deletePostulation' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PostulationController:list' => ['privates', '.service_locator.7Vvo5dt', 'get_ServiceLocator_7Vvo5dtService', true],
            'App\\Controller\\PostulationController:showPost' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PostulationController:updatepost' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\JobsController::list' => '?',
            'App\\Controller\\PostulationController::addPostulation' => '?',
            'App\\Controller\\PostulationController::deletePostulation' => '?',
            'App\\Controller\\PostulationController::list' => '?',
            'App\\Controller\\PostulationController::showPost' => '?',
            'App\\Controller\\PostulationController::updatepost' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\JobsController:list' => '?',
            'App\\Controller\\PostulationController:addPostulation' => '?',
            'App\\Controller\\PostulationController:deletePostulation' => '?',
            'App\\Controller\\PostulationController:list' => '?',
            'App\\Controller\\PostulationController:showPost' => '?',
            'App\\Controller\\PostulationController:updatepost' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
