<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMvlmzTu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMvlmzTu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMvlmzTu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMvlmzTu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMvlmzTu\App_KernelDevDebugContainer([
    'container.build_hash' => 'MvlmzTu',
    'container.build_id' => 'e51caa61',
    'container.build_time' => 1708035003,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMvlmzTu');
