<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCkxZLBd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCkxZLBd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCkxZLBd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCkxZLBd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCkxZLBd\App_KernelDevDebugContainer([
    'container.build_hash' => 'CkxZLBd',
    'container.build_id' => 'a85984e9',
    'container.build_time' => 1707959444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCkxZLBd');
