<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDcyJXRr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDcyJXRr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDcyJXRr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDcyJXRr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDcyJXRr\App_KernelDevDebugContainer([
    'container.build_hash' => 'DcyJXRr',
    'container.build_id' => '7c26fc0c',
    'container.build_time' => 1708373134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDcyJXRr');
