<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_interview' => [[], ['_controller' => 'App\\Controller\\InterviewController::index'], [], [['text', '/interview']], [], [], []],
    'addInterview' => [['id_r', 'id_f'], ['_controller' => 'App\\Controller\\InterviewController::addInterview'], [], [['variable', '/', '[^/]++', 'id_f', true], ['variable', '/', '[^/]++', 'id_r', true], ['text', '/interview/new']], [], [], []],
    'list_interview' => [['id'], ['_controller' => 'App\\Controller\\InterviewController::list'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/interviewlist']], [], [], []],
    'showinterview' => [['id_u', 'id_i'], ['_controller' => 'App\\Controller\\InterviewController::showPost'], [], [['variable', '/', '[^/]++', 'id_i', true], ['variable', '/', '[^/]++', 'id_u', true], ['text', '/interview/details']], [], [], []],
    'deleteinterview' => [['id_u', 'id_i'], ['_controller' => 'App\\Controller\\InterviewController::deleteInterview'], [], [['variable', '/', '[^/]++', 'id_i', true], ['variable', '/', '[^/]++', 'id_u', true], ['text', '/deleteinterview']], [], [], []],
    'updateinterview' => [['id_u', 'id_i'], ['_controller' => 'App\\Controller\\InterviewController::updateinterview'], [], [['variable', '/', '[^/]++', 'id_i', true], ['variable', '/', '[^/]++', 'id_u', true], ['text', '/updateinterview']], [], [], []],
    'list_jobs' => [[], ['_controller' => 'App\\Controller\\JobsController::list'], [], [['text', '/jobs']], [], [], []],
    'app_postulation' => [[], ['_controller' => 'App\\Controller\\PostulationController::index'], [], [['text', '/postulation']], [], [], []],
    'postulate' => [['idFreelancer', 'idJob'], ['_controller' => 'App\\Controller\\PostulationController::addPostulation'], [], [['variable', '/', '[^/]++', 'idJob', true], ['variable', '/', '[^/]++', 'idFreelancer', true], ['text', '/postulation/new']], [], [], []],
    'showpost' => [['id_u', 'id_p'], ['_controller' => 'App\\Controller\\PostulationController::showPost'], [], [['variable', '/', '[^/]++', 'id_p', true], ['variable', '/', '[^/]++', 'id_u', true], ['text', '/postulation']], [], [], []],
    'list_postulation' => [['id'], ['_controller' => 'App\\Controller\\PostulationController::list'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/postulationlist']], [], [], []],
    'deletepost' => [['id_u', 'id_p'], ['_controller' => 'App\\Controller\\PostulationController::deletePostulation'], [], [['variable', '/', '[^/]++', 'id_p', true], ['variable', '/', '[^/]++', 'id_u', true], ['text', '/deletepost']], [], [], []],
    'updatepost' => [['id_u', 'id_p'], ['_controller' => 'App\\Controller\\PostulationController::updatepost'], [], [['variable', '/', '[^/]++', 'id_p', true], ['variable', '/', '[^/]++', 'id_u', true], ['text', '/updatepost']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
